name: CI Admin

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - "admin/**"
      - ".github/workflows/ci-admin.yml"
      - ".github/workflows/verify-admin.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/verify-admin.yml
